x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  amneziawg:
    image: ghcr.io/amnezia-vpn/amneziawg-go:latest
    container_name: amneziawg
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - ./amneziawg:/etc/amneziawg
      - /lib/modules:/lib/modules:ro
    ports:
      - "51820:51820/udp"

  uptime-kuma:
    image: louislam/uptime-kuma:2.3.2
    container_name: uptime-kuma
    logging: *default-logging
    restart: always
    ports:
      - "127.0.0.1:3002:3001"
    volumes:
      - ./uptime-kuma-data:/app/data
    deploy:
      resources:
        limits:
          memory: 512M

  nginx:
    image: nginx:stable
    container_name: nginx_vps
    logging: *default-logging
    restart: always
    network_mode: host
    environment:
      - SYNAPSE_SERVER_NAME=${SYNAPSE_SERVER_NAME}
    volumes:
      - ./nginx/nginx.remote.conf:/etc/nginx/nginx.conf:ro
    deploy:
      resources:
        limits:
          memory: 512M
