x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  frps:
    image: snowdreamtech/frps:latest
    container_name: frps
    logging: *default-logging
    restart: always
    network_mode: host
    environment:
      - FRP_TOKEN=${FRP_TOKEN}
    volumes:
      - ./frp/frps.toml:/etc/frp/frps.toml:ro
    deploy:
      resources:
        limits:
          memory: 512M

  uptime-kuma:
    image: louislam/uptime-kuma:2.3.2
    container_name: uptime-kuma
    logging: *default-logging
    restart: always
    ports:
      - "127.0.0.1:3001:3001"
    volumes:
      - ./uptime-kuma-data:/app/data
    deploy:
      resources:
        limits:
          memory: 512M
  
  uptime-kuma-init:
    image: curlimages/curl
    depends_on:
      - uptime-kuma
    environment:
      - KUMA_URL=http://uptime-kuma:3001
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASS=${ADMIN_PASSWORD}
    logging: *default-logging
    command: >
      sh -c "
      echo 'Ожидание запуска Kuma...';
      until curl -s $KUMA_URL > /dev/null; do sleep 5; done;
      
      echo 'Создание администратора...';
      curl -s -X POST $KUMA_URL/api/v1/setup \
        -H 'Content-Type: application/json' \
        -d '{\"username\":\"$ADMIN_USER\",\"password\":\"$ADMIN_PASS\"}';
      
      echo 'Создание Push-монитора для сервера...';
      TOKEN=$(curl -s -X POST $KUMA_URL/api/v1/login \
        -H 'Content-Type: application/json' \
        -d '{\"username\":\"$ADMIN_USER\",\"password\":\"$ADMIN_PASS\"}' | jq -r '.token');
      
      curl -s -X POST $KUMA_URL/api/v1/monitor \
        -H 'Authorization: Bearer $TOKEN' \
        -H 'Content-Type: application/json' \
        -d '{\"name\":\"Home-Server\",\"type\":\"push\",\"heartbeat\":60}';
      "
    deploy:
      resources:
        limits:
          memory: 512M